config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :tasks, except: %i[show edit update destroy]
  resources :groups, except: %i[update destroy]
  get '/about', to: 'static_pages#about'
  get '/home', to: 'static_pages#home'

  root to: "static_pages#landing"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_dashboard.html.erb
<div class="items-container">
  <%= yield :total_time %>
  <% if locals[:itemizable].length != 0 %>
    <ul class="items-list" id="items-list">
      <%= render partial: 'shared/items', collection: locals[:itemizable],
        as: :itemizables, locals: { linkable: locals[:linkable] } %>
    </ul>
  <% else %>
    <div class="empty-list">
      There's nothing here :c
    </div>
  <% end %>
</div>

app/views/shared/_items.html.erb
<li class="items-entry">
  <%= image_tag  self.uncache_icons(itemizables), class: 'group-avatar' %>
  <div class="item-details">
    <div class="item-text">
      <div class="item-name"><%= itemizables[:name] %></div>
      <div class="item-date"><%= date_helper itemizables[:created_at] %></div>
    </div>
    <div class="item-app">
    <% if itemizables[:amount] %>
      <%= to_time_format(itemizables[:amount]) %>
    <% end %>
  </div>
  </div>
  <% if linkable %>
    <%= link_to nil, itemizables, class: 'item-link-cover' %>
  <% end %>
</li>

app/views/shared/_menu.html.erb
<% if user_signed_in? %>
<div class='menu-container'>
  <nav class="menu-poppable" id="menu-poppable" >
    <div class="menu-user-container">
      <%= image_tag  current_user.icon_url, class: 'user-avatar' %>
      <div class="user-name"><%= current_user.name %></div>
    </div>
    <ul class="menu-list">
      <li class="menu-item">
        <%= image_tag  "tasks-icon.png", class: "menu-list-icon" %>
        <%= link_to  'My tasks', tasks_path(internal: true) %>
      </li>
      <li class="menu-item">
        <%= image_tag  "external-icon.png", class: "menu-list-icon" %>
        <%= link_to  'My external tasks', tasks_path %>
      </li>
      <li class="menu-item">
        <%= image_tag  "groups-icon.png", class: 'menu-list-icon' %>
        <%= link_to  'Groups', groups_path %>
      </li>
      <li class="menu-item">
        <%= image_tag  "logout-icon.png", class: "menu-list-icon" %>
        <%= link_to  'Logout', destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </nav>
</div>
<% end %>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="flash-container flash-success" id="flash-notice">
    <div><%= notice %></div>
  </div>
<% end %>
<% if alert %>
  <div class="flash-container flash-error" id="flash-alert">
    <div><%= alert %></div>
  </div>
<% end %>
<% if  flash[:success] %>
  <div class="flash-container flash-success" id="flash-sucess">
    <div><%= flash[:success] %></div>
  </div>
<% end %>
<% if  flash[:error]%>
  <div class="flash-container flash-error" id="flash-error">
    <div><%= flash[:error] %></div>
  </div>
<% end %>

app/views/shared/_status.html.erb
<% if controller_name != 'static_pages' %>
  <div class="status-bar">
    <%if user_signed_in? %>
      <a class="menu-popper" id="menu-popper" >
        <div class="menu-bar1" id="menu-bar1"></div>
        <div class="menu-bar2"></div>
        <div class="menu-bar3" id="menu-bar3"></div>
      </a>
    <% elsif content_for?(:back_button) %>
      <%= yield :back_button %>
    <% end %>
    <h2 class="status"><%= title_helper( yield :title ) %></h2>
    <%= action_button_helper( yield :action_button )%>
    <%= yield :search %>
  </div>
<% end %>